[package]
name = "repository"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
rand = "0.8.5"
rusqlite = { version = "0.32.1", features = ["bundled"]}
walkdir = "2.5.0"
